[project]
name = "pbi-metadata-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lz4>=4.4.4",
    "openpyxl>=3.1.5",
    "streamlit>=1.50.0",
]
